// dit zijn alle fortunes die ik kon bedenken

const toekomst = [
    `De uitkomst van de loterij blijft onbekend tot de uitslag.`,
    `Helaas, je raakt je sleutels kwijt.`,
    `In de nabije toekomst vind je een appel.`,
    `Als je links kijkt, zie je rechts niets.`,
    `Waar is het feestje? Je weet het niet, want je bent niet uitgenodigd.`,
    `Wanneer je een boom ziet, heeft deze waarschijnlijk takken.`,
    `Ik voorspel dat je vandaag een kleur zal zien, tenzij je (kleuren)blind bent.`,
    `Je zal een onbekende man tegenkomen in de supermarkt.`,
    `Vandaag ga je waarschijnlijk een keer naar het toilet.`,
    `Ik voorspel hoofdpijn. Vergeet niet om water te drinken.`,
    `Ik weet dat je wel eens vergeet je tanden te poetsen.`,
    `Controleer even of je de deur wel op slot hebt gedaan!`,
    `Born to be alive is níet van The Village People!! `,
    `Heb je al in dat ene keukenlaatje gekeken?`,
    `Vraag het morgen nog eens, dan heb je meer geluk.`,
    `Je eet waarschijnlijk vanavond geen pizza, maar als je dat wel doet - eet smakelijk!.`,
    `Is het koud buiten? Trek dan een jas aan voor je vertrekt.`,
    `Je haar zit wel prima vandaag. `,
    `Hoe het klokje thuis tikt, tikt het nergens, want het klokje is thuis. `,
    `Liever een gat in je sok, dan een sok in je gat. `,
    `Als achter vliegen vliegen vliegen, is het tijd om de vuilniszak te vervangen. `,
    `Vergeet je vitamientjes niet in te nemen vandaag. `,
    `Leuke schoenen heb je aan. Tenzij je geen schoenen aanhebt. `,
    `Soms komt er een punt waarop jij ergens niets meer aan kunt doen. `,
    `Over het algemeen is de kans relatief groot dat je vandaag wat gezonder had kunnen eten. `,
    `Maak een boodschappenlijstje voor je naar de supermarkt gaat. `,
    `Eet elke dag een appel, anders word je kaal. `,
    `Vandaag zal je niet één, maar wel twéé keer je eigen spiegelbeeld zien. `,
    `Je toekomst is wazig. Probeer het later nog eens. `,
    `Ik voorzie dat je binnen nu en honderd jaar zal sterven. `,
];
